### ISSUE TITLE
css variables are not compatible with IE 11

### ISSUE THREAD

**Issue by danverde** [byuitechops/byui-canvas-theme#50]

**Comment by meeple142** [comment]
Yeah we knew this. And decided to be okay with the default colors in those given courses. although we probably should make sure that everybody understands that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danverde** [comment]
The default colors aren't always working. In the example below the week buttons exist, but don't have a background color so you can't see them.
![broken css](https://user-images.githubusercontent.com/19293059/45834236-e582cf80-bcc3-11e8-9019-5bebcf3bd4b4.JPG)

**Comment by meeple142** [comment]
Oh! well.. that's definitely not good

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danverde** [comment]
I've seen it in the WYSIWYG as well.
