### ISSUE TITLE
BYUI Copyright Footer Throwing Error when iFrame is opened

### ISSUE THREAD

**Issue by ajshiff** [byuitechops/byui-canvas-theme#57]
Specifically when using the BYUI Toolbox on Canvas, this error shows up: 
```
VM201 byui.js:1 unable to add copyright footer to page
(anonymous) @ VM201 byui.js:1
main @ VM201 byui.js:1
```
```
VM202 byui.js:235 Error: unable to add copyright footer to page
    at addCopyrightFooter (byui.js:232)
    at HTMLDocument.main (byui.js:284)
addCopyrightFooter @ VM202 byui.js:235
main @ VM202 byui.js:284
```
It is unable to add the copyright footer to the iFrame, and throws this error. It doesn't cause the whole program to collapse, but it may still be a good idea to either allow it to add the footer, or not. Josh knows about this, and so does Aaron, so if there are any questions, you can ask one of them.

**Comment by danverde** [comment]
After thinking about this for a while I think it would be best to leave the error message as is, and alter the v-tool so that it contains a `#copyright` element. If we want the copyright footer to show up on the page (which we do) this will be the best solution.
