### ISSUE TITLE
Have the version number inside the js and css file

### ISSUE THREAD

**Issue by meeple142** [byuitechops/byui-canvas-theme#65]
when we build the prod versions we need to have the version number inside the js file so that we can see instantly what version number is running in anywhere.

**Comment by emmafisher1720** [comment]
I've fixed this in the dev branch. Just run npm version major, minor, patch and it will:
* update the version in the package.json
* add a comment with the version in CSS and JS files
* add a git tag with the version
* add, commit, and push the changes
* merge with master
