### ISSUE TITLE
make a callout with a picture

### ISSUE THREAD

**Issue by meeple142** [byuitechops/byui-canvas-theme#73]
they want the picture to wrap but when there is not a lot of space to behave nicely like a full width or block. There are ones that have video too but the video is in the middle of the text box.

**Comment by meeple142** [comment]
could do it picture to the left and text to the right  or top and bottom on phones. that way we don't have to worry about floating

**Comment by danverde** [comment]
@meeple142 If I understand correctly, They want to be able to wrap images around text within the callout?

**Comment by emmafisher1720** [comment]
Look into callouts, their structure, and fix our CSS and HTML in the V tool. Set up a meeting with Shaun Short and his student
